name: Deploy Arden Github pages

on:
  push:
    branches:
      - main
      - gh-pages
jobs:
  build:
    runs-on:
      ubuntu-latest
      #步骤合集
    steps:
      #新建一个名为checkout_actions的步骤
      - name: checkout_actions
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v2
      #使用建一个名为setup-node的步骤
      - name: setup-node
        #使用setup-node@v1这个action
        uses: actions/setup-node@v1
        #指定某个action 可能需要输入的参数
        with:
          node-version: '15'
      - name: npm install and build
      # #执行执行某个shell命令或脚本
        run: |
          npm install
        run: |
          npm start
          npm build

